name: Trigger auto deployment for uptimekuma

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/uptimekuma-AutoDeployTrigger-4c0ae8fd-53fb-4019-b9c2-bb83f5dbdd2a.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPTIMEKUMA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.UPTIMEKUMA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.UPTIMEKUMA_REGISTRY_PASSWORD }}
          containerAppName: uptimekuma
          resourceGroup: rg-network
          imageToBuild: louislam/uptime-kuma:${{ github.sha }}
          

     

